#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Manual entry for win10 (not working because disk not recognised

#menuentry "Windows 10" {
#insmod ntfs
#set root='(hd0,0)'
#search --no-floppy --fsuuid --set EA5A-2930
#chainloader +1
#}
