#!/bin/sh
#xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

#/usr/bin/qiv -z /home/rupioe/Downloads/ba-lxdm.png
#xrandr -s 1920x1080
#xloadimage -onroot -quiet -fullscreen /etc/X11/xdm/archlinux/ba-lxdm.png
